#!/bin/bash
sudo apt-get update
sudo apt-get install git-all
for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt install zsh
sudo apt install neovim
sudo apt install build-essential
sudo apt install curl
sudo apt install gh
sudo apt install feh
cd ~/.config 
git clone https://github.com/JeppeOEM/nvim.git
mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf
cd
curl -L -R -O https://www.lua.org/ftp/lua-5.4.6.tar.gz
tar zxf lua-5.4.6.tar.gz
cd lua-5.4.6
make all test
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

sudo apt install fd-find
sudo apt install ripgrep
sudo docker run hello-world
chsh -s $(which zsh)
cd ~/scripts
chmod 755 add_to_zshrc
./add_to_zshrc fd zsh-syntax-highlighting zsh-autosuggestions
cat << 'EOF' >> ~/.zshrc

# Custom function to check for virtual environment
pip() {
    if [ -z "\$VIRTUAL_ENV" ]; then
        echo "Error: You are not in a virtual environment. Please activate a virtual environment before using pip."
    else
        command pip "\$@"
    fi
}
EOF

source ~/.zshrc
sudo apt update
sudo apt install nodejs
sudo apt install npm
